#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Mar  6 10:01:51 2018

@author: s1749290
"""

import numpy as np
import matplotlib.pyplot as plt

x = np.loadtxt('saved_models/adam_10x4_24h_2l/sorts.txt')

plt.plot(x)